service:
  registry:
    #本机的地址和本项目的端口 本地开发时负载均衡优先路由到本地
    expose-host: ${expose.host:192.168.3.45}
    expose-port: ${expose.port:9703}
    #注册中心的地址和注册中心的端口号 一般设置为服务器的地址
    consul-host: ${consul.host:47.106.153.232}
    consul-port: ${consul.port:8500}

spring:
  datasource:
    name: main0
    url: jdbc:mysql://47.106.153.232:3306/dd_main0?useUnicode=true&characterEncoding=utf8
    username: fangln
    password: fangln1991!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-interval: 5s
        service-name: ${spring.application.name}
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}${management.server.servlet.context-path}/info
        enabled: true
        # 默认设置queryPassing=false，即返回所有的服务，包括down掉的。通过配置改为true则可返回所有健康检查通过的服务
        query-passing: true
        prefer-ip-address: true

#  rabbitmq:
#    addresses: 192.168.4.202:5672
#    username: admin
#    password: poly2017
#    virtual-host: /
#    connection-timeout: 120000
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true
#    listener:
#      simple:
#        acknowledge-mode: manual  #none不发送ack。manual手工签收。auto自动ack
#        concurrency: 5  #最小消费者数量
#        max-concurrency: 10  #最大消费者数量
#  redis:
#    database: 0
#    host: 192.168.4.205
#    port: 6379

#token:
#  jwtSecret: propertyCloud2019  #jwt secret

