service:
  registry:
    #本机的地址和本项目的端口 本地开发时负载均衡优先路由到本地
    expose-host: ${expose.host:192.168.3.45}
    expose-port: ${expose.port:9701}
    #注册中心的地址和注册中心的端口号 一般设置为服务器的地址
    consul-host: ${consul.host:47.106.153.232}
    consul-port: ${consul.port:8500}

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      main:
        url: jdbc:mysql://47.106.153.232:3306/dd_main0?useUnicode=true&characterEncoding=utf8
        username: fangln
        password: fangln1991!
      robot:
        url: jdbc:mysql://47.106.153.232:3306/fly_robot?useUnicode=true&characterEncoding=utf8
        username: fangln
        password: fangln1991!
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      validationQueryTimeout: 3
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-interval: 5s
        service-name: ${spring.application.name}
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}${management.server.servlet.context-path}/info
        enabled: true
        # 默认设置queryPassing=false，即返回所有的服务，包括down掉的。通过配置改为true则可返回所有健康检查通过的服务
        query-passing: true
        prefer-ip-address: true
#  redis:
#    database: 0
#    host: 192.168.4.205
#    port: 6379

token:
  jwtSecret: propertyCloud2019  #jwt secret

